//
// Created by c0025512 on 23/05/2023.
//

#ifndef APPOINTMENT_BOOKING_SYSTEM_APPOINTMENT_H
#define APPOINTMENT_BOOKING_SYSTEM_APPOINTMENT_H

typedef struct Client_Appointment{

} Appt;

#endif //APPOINTMENT_BOOKING_SYSTEM_APPOINTMENT_H
